-- ============================================================================
-- EduCare Management System
-- EDGE (EduCare Data Generator Engine)
-- ----------------------------------------------------------------------------
-- Seed: 006_employees.sql
--
-- Purpose
-- --------
-- Creates employee records for the first 110 staff users:
--
--   User 1       SUPER_ADMIN
--   Users 2-5   SCHOOL_ADMIN
--   Users 6-85   TEACHER
--   Users 86-110 SCHOOL_ADMIN
--
-- Total employees: 110
--
-- Department IDs are resolved using department_code.
-- Position IDs are resolved from active positions belonging
-- to the selected department.
--
-- Safe to rerun:
-- Existing generated employee records are removed first.
-- ============================================================================

BEGIN;

-- ============================================================================
-- Remove existing generated employee records
--
-- Employee numbers generated by this seed use the EMP- prefix.
-- ============================================================================

DELETE FROM employees
WHERE employee_number LIKE 'EMP-%';

-- ============================================================================
-- Generate employees for users 1-110
-- ============================================================================

INSERT INTO employees
(
    user_id,
    school_id,
    department_id,
    position_id,
    employee_number,
    employment_type,
    employment_status,
    hire_date,
    termination_date,
    salary,
    is_active
)

SELECT
    u.id AS user_id,

    -- ========================================================================
    -- School assignment
    --
    -- Distributes employees across all existing schools.
    -- ========================================================================

    s.school_id,

    -- ========================================================================
    -- Department assignment
    --
    -- SUPER_ADMIN
    --     Administration
    --
    -- SCHOOL_ADMIN
    --     Distributed across Administration, Finance, HR, ICT and
    --     Student Affairs.
    --
    -- TEACHER
    --     Primarily Academics with some Sports assignments.
    -- ========================================================================

    d.id AS department_id,

    -- ========================================================================
    -- Position assignment
    --
    -- Selects a position belonging to the employee's department.
    -- ========================================================================

    p.id AS position_id,

    -- ========================================================================
    -- Employee number
    -- ========================================================================

    'EMP-' || LPAD(u.id::TEXT, 4, '0'),

    -- ========================================================================
    -- Employment type
    -- ========================================================================

    CASE

        WHEN u.role = 'TEACHER'
            THEN 'FULL_TIME'::employment_type

        WHEN u.role = 'SUPER_ADMIN'
            THEN 'FULL_TIME'::employment_type

        ELSE
            CASE (u.id % 4)
                WHEN 0 THEN 'FULL_TIME'::employment_type
                WHEN 1 THEN 'PART_TIME'::employment_type
                WHEN 2 THEN 'CONTRACT'::employment_type
                ELSE 'FULL_TIME'::employment_type
            END

    END,

    -- ========================================================================
    -- Employment status
    -- ========================================================================

    CASE
        WHEN u.id % 20 = 0
            THEN 'ON_LEAVE'::employment_status

        WHEN u.id % 37 = 0
            THEN 'SUSPENDED'::employment_status

        ELSE
            'ACTIVE'::employment_status
    END,

    -- ========================================================================
    -- Hire date
    -- ========================================================================

    CURRENT_DATE
        - ((u.id % 3650) + 180)::INTEGER,

    -- ========================================================================
    -- Termination date
    --
    -- Current generated staff remain employed.
    -- ========================================================================

    NULL,

    -- ========================================================================
    -- Salary
    -- ========================================================================

    CASE

        WHEN u.role = 'SUPER_ADMIN'
            THEN 85000.00

        WHEN u.role = 'SCHOOL_ADMIN'
            THEN
                CASE (u.id % 5)
                    WHEN 0 THEN 52000.00
                    WHEN 1 THEN 48000.00
                    WHEN 2 THEN 45000.00
                    WHEN 3 THEN 42000.00
                    ELSE 39000.00
                END

        WHEN u.role = 'TEACHER'
            THEN
                CASE (u.id % 5)
                    WHEN 0 THEN 42000.00
                    WHEN 1 THEN 39000.00
                    WHEN 2 THEN 36000.00
                    WHEN 3 THEN 33000.00
                    ELSE 30000.00
                END

        ELSE
            30000.00

    END,

    TRUE

FROM users u

-- ============================================================================
-- Only the first 110 users are employees.
-- ============================================================================

JOIN LATERAL
(
    SELECT
        sc.id AS school_id
    FROM schools sc
    ORDER BY sc.id
    OFFSET ((u.id - 1) % GREATEST(
        (SELECT COUNT(*) FROM schools),
        1
    ))
    LIMIT 1
) s
    ON TRUE

-- ============================================================================
-- Department selection
-- ============================================================================

JOIN departments d
    ON d.department_code =
        CASE

            -- Super administrator
            WHEN u.role = 'SUPER_ADMIN'
                THEN 'ADMIN'

            -- Teachers
            WHEN u.role = 'TEACHER'
                THEN
                    CASE
                        WHEN u.id % 15 = 0
                            THEN 'SPORT'
                        ELSE
                            'ACAD'
                    END

            -- School administrators
            WHEN u.role = 'SCHOOL_ADMIN'
                THEN
                    CASE (u.id % 5)
                        WHEN 0 THEN 'ADMIN'
                        WHEN 1 THEN 'FIN'
                        WHEN 2 THEN 'HR'
                        WHEN 3 THEN 'ICT'
                        ELSE 'STU'
                    END

            ELSE
                'ADMIN'

        END

-- ============================================================================
-- Position selection
-- ============================================================================

JOIN LATERAL
(
    SELECT
        pp.id
    FROM positions pp
    WHERE pp.department_id = d.id
      AND pp.is_active = TRUE
      AND
      (
          -- ================================================================
          -- SUPER_ADMIN
          -- ================================================================

          (
              u.role = 'SUPER_ADMIN'
              AND pp.position_code = 'SADM'
          )

          OR

          -- ================================================================
          -- TEACHERS - ACADEMICS
          --
          -- Most teachers receive the normal Teacher position.
          -- Selected teachers receive senior academic/coordinator roles.
          -- Principal and Deputy Principal are excluded.
          -- ================================================================

          (
              u.role = 'TEACHER'
              AND d.department_code = 'ACAD'
              AND pp.position_code =
                  CASE
                      WHEN u.id % 20 = 0
                          THEN 'HOD'

                      WHEN u.id % 25 = 0
                          THEN 'ACADCO'

                      WHEN u.id % 30 = 0
                          THEN 'CURRCO'

                      ELSE
                          'TCHR'
                  END
          )

          OR

          -- ================================================================
          -- TEACHERS - SPORTS
          -- ================================================================

          (
              u.role = 'TEACHER'
              AND d.department_code = 'SPORT'
              AND pp.position_code =
                  CASE
                      WHEN u.id % 30 = 0
                          THEN 'PECO'

                      WHEN u.id % 20 = 0
                          THEN 'HCOACH'

                      ELSE
                          'COACH'
                  END
          )

          OR

          -- ================================================================
          -- SCHOOL ADMINISTRATORS
          --
          -- Selects positions appropriate to their department.
          -- ================================================================

          (
              u.role = 'SCHOOL_ADMIN'
              AND
              pp.position_code =
                  CASE d.department_code

                      WHEN 'ADMIN' THEN
                          CASE (u.id % 5)
                              WHEN 0 THEN 'SADM'
                              WHEN 1 THEN 'RECEP'
                              WHEN 2 THEN 'REG'
                              WHEN 3 THEN 'ADMS'
                              ELSE 'EXECASST'
                          END

                      WHEN 'FIN' THEN
                          CASE (u.id % 5)
                              WHEN 0 THEN 'FINMGR'
                              WHEN 1 THEN 'ACCT'
                              WHEN 2 THEN 'ACCTCLERK'
                              WHEN 3 THEN 'PAYROLL'
                              ELSE 'BURSAR'
                          END

                      WHEN 'HR' THEN
                          CASE (u.id % 5)
                              WHEN 0 THEN 'HRMGR'
                              WHEN 1 THEN 'HROFF'
                              WHEN 2 THEN 'RECRUIT'
                              WHEN 3 THEN 'EREL'
                              ELSE 'TRAINCO'
                          END

                      WHEN 'ICT' THEN
                          CASE (u.id % 5)
                              WHEN 0 THEN 'ICTMGR'
                              WHEN 1 THEN 'SYSADMIN'
                              WHEN 2 THEN 'NETADMIN'
                              WHEN 3 THEN 'ITSUP'
                              ELSE 'DBADMIN'
                          END

                      WHEN 'STU' THEN
                          CASE (u.id % 5)
                              WHEN 0 THEN 'SAMGR'
                              WHEN 1 THEN 'COUNSEL'
                              WHEN 2 THEN 'STUSUP'
                              WHEN 3 THEN 'LAC'
                              ELSE 'ACTCO'
                          END

                  END
          )

      )
    LIMIT 1
) p
    ON TRUE

WHERE u.id BETWEEN 1 AND 110;

-- ============================================================================
-- Finish transaction
-- ============================================================================

COMMIT;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Total employees
SELECT
    COUNT(*) AS total_employees
FROM employees;

-- Employees by user role
SELECT
    u.role,
    COUNT(e.id) AS total_employees
FROM employees e
JOIN users u
    ON u.id = e.user_id
GROUP BY u.role
ORDER BY u.role;

-- Employees by department
SELECT
    d.department_name,
    d.department_code,
    COUNT(e.id) AS total_employees
FROM employees e
JOIN departments d
    ON d.id = e.department_id
GROUP BY
    d.id,
    d.department_name,
    d.department_code
ORDER BY d.id;

-- Employees by employment type
SELECT
    employment_type,
    COUNT(*) AS total
FROM employees
GROUP BY employment_type
ORDER BY employment_type;

-- Employees by employment status
SELECT
    employment_status,
    COUNT(*) AS total
FROM employees
GROUP BY employment_status
ORDER BY employment_status;

-- Check employee-number uniqueness
SELECT
    COUNT(*) AS total_employee_numbers,
    COUNT(DISTINCT employee_number) AS unique_employee_numbers
FROM employees;

-- Check for invalid department/position combinations
SELECT
    e.id,
    e.employee_number,
    e.department_id,
    e.position_id
FROM employees e
JOIN positions p
    ON p.id = e.position_id
WHERE p.department_id <> e.department_id;

-- Detailed employee list
SELECT
    e.id,
    e.employee_number,
    u.first_name,
    u.last_name,
    u.role,
    s.id AS school_id,
    d.department_name,
    p.position_name,
    p.position_code,
    e.employment_type,
    e.employment_status,
    e.hire_date,
    e.salary,
    e.is_active
FROM employees e
JOIN users u
    ON u.id = e.user_id
JOIN schools s
    ON s.id = e.school_id
JOIN departments d
    ON d.id = e.department_id
JOIN positions p
    ON p.id = e.position_id
ORDER BY e.id
LIMIT 110;