-- ============================================================
-- EduCare Management System
-- Migration 002: Library Management
-- ============================================================
-- Creates:
--   1. book_copies
--   2. library_members
--   3. library_loans
--   4. library_fines
--
-- Existing books.author and books.category fields are retained.
-- Authors/categories can be normalized in a future migration if needed.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. BOOK COPIES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.book_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    book_id BIGINT NOT NULL,
    school_id BIGINT NOT NULL,

    copy_number INTEGER NOT NULL,
    barcode VARCHAR(100),

    acquisition_date DATE,
    purchase_price NUMERIC(12,2),

    condition VARCHAR(30) NOT NULL DEFAULT 'GOOD',
    status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE',

    shelf_location VARCHAR(100),
    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by BIGINT,
    updated_by BIGINT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_book_copies_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_book_copies_book_copy_number
        UNIQUE (book_id, copy_number),

    CONSTRAINT uq_book_copies_barcode
        UNIQUE (barcode),

    CONSTRAINT chk_book_copies_copy_number
        CHECK (copy_number > 0),

    CONSTRAINT chk_book_copies_purchase_price
        CHECK (purchase_price IS NULL OR purchase_price >= 0),

    CONSTRAINT chk_book_copies_condition
        CHECK (
            condition IN (
                'NEW',
                'GOOD',
                'FAIR',
                'DAMAGED',
                'LOST'
            )
        ),

    CONSTRAINT chk_book_copies_status
        CHECK (
            status IN (
                'AVAILABLE',
                'ON_LOAN',
                'RESERVED',
                'LOST',
                'DAMAGED',
                'WITHDRAWN'
            )
        ),

    CONSTRAINT fk_book_copies_book
        FOREIGN KEY (book_id)
        REFERENCES public.books(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_book_copies_school
        FOREIGN KEY (school_id)
        REFERENCES public.schools(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_book_copies_book_id
    ON public.book_copies(book_id);

CREATE INDEX IF NOT EXISTS idx_book_copies_school_id
    ON public.book_copies(school_id);

CREATE INDEX IF NOT EXISTS idx_book_copies_status
    ON public.book_copies(status);

CREATE INDEX IF NOT EXISTS idx_book_copies_barcode
    ON public.book_copies(barcode);


-- ============================================================
-- 2. LIBRARY MEMBERS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.library_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    user_id BIGINT NOT NULL,
    school_id BIGINT NOT NULL,

    learner_id BIGINT,
    employee_id BIGINT,
    guardian_id BIGINT,

    membership_number VARCHAR(50) NOT NULL,

    membership_type VARCHAR(20) NOT NULL DEFAULT 'LEARNER',

    membership_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expiry_date DATE,

    max_books INTEGER NOT NULL DEFAULT 3,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by BIGINT,
    updated_by BIGINT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_library_members_public_id
        UNIQUE (public_id),

    CONSTRAINT uq_library_members_membership_number
        UNIQUE (membership_number),

    CONSTRAINT uq_library_members_user_school
        UNIQUE (user_id, school_id),

    CONSTRAINT chk_library_members_type
        CHECK (
            membership_type IN (
                'LEARNER',
                'EMPLOYEE',
                'GUARDIAN'
            )
        ),

    CONSTRAINT chk_library_members_max_books
        CHECK (max_books > 0),

    CONSTRAINT chk_library_members_dates
        CHECK (
            expiry_date IS NULL
            OR expiry_date >= membership_date
        ),

    CONSTRAINT chk_library_members_status
        CHECK (
            status IN (
                'ACTIVE',
                'SUSPENDED',
                'EXPIRED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_library_members_identity_type
        CHECK (
            (membership_type = 'LEARNER'
                AND learner_id IS NOT NULL
                AND employee_id IS NULL
                AND guardian_id IS NULL)

            OR

            (membership_type = 'EMPLOYEE'
                AND learner_id IS NULL
                AND employee_id IS NOT NULL
                AND guardian_id IS NULL)

            OR

            (membership_type = 'GUARDIAN'
                AND learner_id IS NULL
                AND employee_id IS NULL
                AND guardian_id IS NOT NULL)
        ),

    CONSTRAINT fk_library_members_user
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_members_school
        FOREIGN KEY (school_id)
        REFERENCES public.schools(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_members_learner
        FOREIGN KEY (learner_id)
        REFERENCES public.learners(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_members_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_members_guardian
        FOREIGN KEY (guardian_id)
        REFERENCES public.guardians(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_library_members_user_id
    ON public.library_members(user_id);

CREATE INDEX IF NOT EXISTS idx_library_members_school_id
    ON public.library_members(school_id);

CREATE INDEX IF NOT EXISTS idx_library_members_membership_type
    ON public.library_members(membership_type);

CREATE INDEX IF NOT EXISTS idx_library_members_status
    ON public.library_members(status);


-- ============================================================
-- 3. VALIDATE MEMBER IDENTITY
-- ============================================================
-- Ensures the selected learner/employee/guardian actually
-- belongs to the supplied user and school.

CREATE OR REPLACE FUNCTION public.validate_library_member_identity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.membership_type = 'LEARNER' THEN

        IF NOT EXISTS (
            SELECT 1
            FROM public.learners l
            WHERE l.id = NEW.learner_id
              AND l.user_id = NEW.user_id
              AND l.school_id = NEW.school_id
        ) THEN
            RAISE EXCEPTION
                'Library learner membership is inconsistent with user or school';
        END IF;

    ELSIF NEW.membership_type = 'EMPLOYEE' THEN

        IF NOT EXISTS (
            SELECT 1
            FROM public.employees e
            WHERE e.id = NEW.employee_id
              AND e.user_id = NEW.user_id
              AND e.school_id = NEW.school_id
        ) THEN
            RAISE EXCEPTION
                'Library employee membership is inconsistent with user or school';
        END IF;

    ELSIF NEW.membership_type = 'GUARDIAN' THEN

        IF NOT EXISTS (
            SELECT 1
            FROM public.guardians g
            WHERE g.id = NEW.guardian_id
              AND g.user_id = NEW.user_id
        ) THEN
            RAISE EXCEPTION
                'Library guardian membership is inconsistent with user';
        END IF;

    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_library_member_identity
ON public.library_members;

CREATE TRIGGER trg_validate_library_member_identity
BEFORE INSERT OR UPDATE OF
    user_id,
    school_id,
    learner_id,
    employee_id,
    guardian_id,
    membership_type
ON public.library_members
FOR EACH ROW
EXECUTE FUNCTION public.validate_library_member_identity();


-- ============================================================
-- 4. LIBRARY LOANS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.library_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    school_id BIGINT NOT NULL,

    book_copy_id BIGINT NOT NULL,
    library_member_id BIGINT NOT NULL,

    loan_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,

    returned_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'BORROWED',

    renewal_count INTEGER NOT NULL DEFAULT 0,

    issued_by BIGINT,
    returned_to BIGINT,

    notes TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by BIGINT,
    updated_by BIGINT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_library_loans_public_id
        UNIQUE (public_id),

    CONSTRAINT chk_library_loans_dates
        CHECK (
            due_date >= loan_date
            AND (
                returned_date IS NULL
                OR returned_date >= loan_date
            )
        ),

    CONSTRAINT chk_library_loans_renewal_count
        CHECK (renewal_count >= 0),

    CONSTRAINT chk_library_loans_status
        CHECK (
            status IN (
                'BORROWED',
                'RETURNED',
                'OVERDUE',
                'LOST',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_library_loans_status_dates
        CHECK (
            (
                status = 'RETURNED'
                AND returned_date IS NOT NULL
            )
            OR
            (
                status IN ('BORROWED', 'OVERDUE', 'LOST')
                AND returned_date IS NULL
            )
            OR
            (
                status = 'CANCELLED'
                AND returned_date IS NULL
            )
        ),

    CONSTRAINT fk_library_loans_school
        FOREIGN KEY (school_id)
        REFERENCES public.schools(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_loans_book_copy
        FOREIGN KEY (book_copy_id)
        REFERENCES public.book_copies(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_loans_member
        FOREIGN KEY (library_member_id)
        REFERENCES public.library_members(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_loans_issued_by
        FOREIGN KEY (issued_by)
        REFERENCES public.users(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_loans_returned_to
        FOREIGN KEY (returned_to)
        REFERENCES public.users(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_library_loans_school_id
    ON public.library_loans(school_id);

CREATE INDEX IF NOT EXISTS idx_library_loans_book_copy_id
    ON public.library_loans(book_copy_id);

CREATE INDEX IF NOT EXISTS idx_library_loans_member_id
    ON public.library_loans(library_member_id);

CREATE INDEX IF NOT EXISTS idx_library_loans_status
    ON public.library_loans(status);

CREATE INDEX IF NOT EXISTS idx_library_loans_due_date
    ON public.library_loans(due_date);

-- Only one active loan may exist for a copy.
CREATE UNIQUE INDEX IF NOT EXISTS uq_library_loans_active_copy
    ON public.library_loans(book_copy_id)
    WHERE is_active = TRUE
      AND returned_date IS NULL
      AND status IN (
          'BORROWED',
          'OVERDUE',
          'LOST'
      );


-- ============================================================
-- 5. LIBRARY FINES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.library_fines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),

    school_id BIGINT NOT NULL,

    loan_id BIGINT NOT NULL,
    library_member_id BIGINT NOT NULL,

    fine_type VARCHAR(30) NOT NULL,

    amount NUMERIC(12,2) NOT NULL,
    amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,

    issued_date DATE NOT NULL DEFAULT CURRENT_DATE,
    paid_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'OUTSTANDING',

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_by BIGINT,
    updated_by BIGINT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_library_fines_public_id
        UNIQUE (public_id),

    CONSTRAINT chk_library_fines_amount
        CHECK (amount > 0),

    CONSTRAINT chk_library_fines_amount_paid
        CHECK (
            amount_paid >= 0
            AND amount_paid <= amount
        ),

    CONSTRAINT chk_library_fines_dates
        CHECK (
            paid_date IS NULL
            OR paid_date >= issued_date
        ),

    CONSTRAINT chk_library_fines_type
        CHECK (
            fine_type IN (
                'OVERDUE',
                'LOST_BOOK',
                'DAMAGED_BOOK',
                'OTHER'
            )
        ),

    CONSTRAINT chk_library_fines_status
        CHECK (
            status IN (
                'OUTSTANDING',
                'PARTIALLY_PAID',
                'PAID',
                'WAIVED'
            )
        ),

    CONSTRAINT fk_library_fines_school
        FOREIGN KEY (school_id)
        REFERENCES public.schools(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_fines_loan
        FOREIGN KEY (loan_id)
        REFERENCES public.library_loans(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_library_fines_member
        FOREIGN KEY (library_member_id)
        REFERENCES public.library_members(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_library_fines_school_id
    ON public.library_fines(school_id);

CREATE INDEX IF NOT EXISTS idx_library_fines_loan_id
    ON public.library_fines(loan_id);

CREATE INDEX IF NOT EXISTS idx_library_fines_member_id
    ON public.library_fines(library_member_id);

CREATE INDEX IF NOT EXISTS idx_library_fines_status
    ON public.library_fines(status);


-- ============================================================
-- 6. COMMENTS
-- ============================================================

COMMENT ON TABLE public.book_copies IS
    'Physical copies of library books owned by a school.';

COMMENT ON TABLE public.library_members IS
    'Users registered as members of the school library.';

COMMENT ON TABLE public.library_loans IS
    'Library borrowing transactions for physical book copies.';

COMMENT ON TABLE public.library_fines IS
    'Fines associated with library loans.';


COMMIT;